### ISSUE TITLE
Repetitive Reviews scrapped 

### ISSUE THREAD

**Issue by lujia1210** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#11]
Hi, I am a newbie to web scrapping and I followed the code to scape 
https://www.tripadvisor.co.za/Restaurant_Review-g294265-d3735954-Reviews-Haidilao_Hot_Pot-Singapore.html
this webpage and found that the final csv file contains repetitive reviews. After inspection, I noticed that the code only managed to scrap the first page of the review and just kept repeating the same page scrapping for multiple times. 
Can you please advise? 
Thank you so much!

**Comment by GNFu** [comment]
I think it may due to the cookies issue since TripAdvisor requires you to click on the "accept cookies button" to go to the next page. You may add on this line after `driver.get(url)`:
`driver.find_element_by_xpath("//*[@id='_evidon-accept-button']").click()`
Hope this can solve your issue.
