### ISSUE TITLE
problem in finding the accurate path

### ISSUE THREAD

**Issue by abu-kaium** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#12]
Hey,
I am getting the following errors:
File "C:/Users/kaium/Scraping-TripAdvisor-with-Python-2020-master/restaurants_scraper.py", line 26, in <module>
    csvFile = open(path_to_file, 'a', encoding="utf-8")
OSError: [Errno 22] Invalid argument: 'E:\x07liza'

please have a look. Hope you can solve the issue. Thanks in advance!

**Comment by moreaupascal56** [comment]
hey, it isweird that you have an error here, I guess you've found by now, but if you did not what is your path ?

**Comment by giuseppegambino** [comment]
Hello @abu-kaium, sorry for the delay

Mmm, sorry for my easy question but are you sure you are using the right path? I don't know you OS but try to use backslash instead of slash
