### ISSUE TITLE
Cannot push branch and open PR 

### ISSUE THREAD

**Issue by moreaupascal56** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#13]
Hello @giuseppegambino ! 👍 
I just wanted to try the code and made some adjustments for firefox and the new cookie SDK used by tripadvisor but I cannot push my branch to the repo. Could you have a look at the permissions ? 
Thx and have great EOY celebrations 🍾 🎉

**Comment by giuseppegambino** [comment]
Hello @moreaupascal56 
mmm I'm not very clear about the problem, sorry

couldn't you do a pull request? 

If you can tell me the difference and if so, what to do to solve the problem,
I would be happy to help you

Happy 2022 :)
