### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by joaofreitas1223** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#15]
Hello Giuseppe. I'm currently writing my master thesis and would like to use this code for scraping hotel reviews, is that okay? It's really important for me. If so, would you kindly put a license so I can use it? Or else I can't, and this is the only code for scraping reviews that has been working for me. Thank you very much.

**Comment by giuseppegambino** [comment]
Hello joao, this night i will try to put the license :) i'm glad that my
code can help you! Keep in touch for any news about this license

Il giorno mer 6 lug 2022 alle 19:56 joaofreitas1223 <
***@***.***> ha scritto:

**Comment by joaofreitas1223** [comment]
Thank you so much for your kindness! I can't thank you enough for trying to put the license tonight, it's really important so I can finish my work. Yes we'll keep in touch.

**Comment by giuseppegambino** [comment]
Just to try to do it faster, do you know how I can put the license on?
Anyway if you don't know about it, i will search on google😂

Il giorno mer 6 lug 2022 alle 20:05 joaofreitas1223 <
***@***.***> ha scritto:

**Comment by joaofreitas1223** [comment]
I hope this helps, I just tried it and it worked. You can choose the MIT License.

Steps:
- browse to your repository at (https://github.com/)
- create a new file by pressing the blue + icon (updated to: New File button)
- name it LICENSE.md or LICENSE.txt to show up the license picker again
- choose a template

**Comment by giuseppegambino** [comment]
Hello Joao, i think that i did it! let me know if it's work.
If you need a reference too, you can cite my paper:
https://www.semanticscholar.org/paper/Investigating-Embeddings-for-Sentiment-Analysis-in-Gambino-Pirrone/0fab5e63809a2f5aea64dfdfe59ebd696db8a3a6,
where in the paragraph "3.1 Data sets" in the section "TripAdvisor
Dataset", i shortly (very shortly) introduce the argument and you can find
the quote below with the github link.

In any case, good luck with your thesis!! :)

Il giorno mer 6 lug 2022 alle ore 20:17 joaofreitas1223 <
***@***.***> ha scritto:

**Comment by joaofreitas1223** [comment]
I can't thank you enough for your kindness. Thank you so much, it worked. I will definitely reference you in my work. :)
