### ISSUE TITLE
TripAdvisor Massive Changes

### ISSUE THREAD

**Issue by edgemund** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#2]
Thanks for your assistance the other time.

It's so so surprising that TripAdvisor has change a lot of things about their web html codes. 
Well, I have managed to write and modify your codes to fit the new changes on their website.

Unfortunately for me, the new scrapy code I have ONLY scrapes the first review of each review page.

I will really appreciate if you can help me finish this code to scrap all reviews on a page. 

Also you can look at how to capture the date {MM:YY} too.

Do reach me at esowah2000atgmail.

[LouvreMuseum.zip](https://github.com/giuseppegambino/Scraping-TripAdvisor-with-Python-2019/files/4289764/LouvreMuseum.zip)
com

**Comment by ManuelBanza** [comment]
Hi @edgemund ,
Did you manage to finished your code?
Cheers!

**Comment by giuseppegambino** [comment]
Hi @edgemund , I finally updated the code. 

Now you can also store the date and title of the reviews, try it and let me know!
