### ISSUE TITLE
'charmap' codec can't encode character '\U0001f60d' in position 107: character maps to <undefined>

### ISSUE THREAD

**Issue by supryzhu** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#3]
![Capture](https://user-images.githubusercontent.com/47655602/87896759-5c7d8080-ca73-11ea-81aa-4a04d863ecbd.JPG)

**Comment by TommasoManzana** [comment]
Pass ` encoding='utf-8'` as an argument to the `csvFile = open()` function

**Comment by giuseppegambino** [comment]
Hi @supryzhu, if you use python3 you will not have any problems with the encoding because is native with utf-8

Thank you @TommasoManzana for your solution
