### ISSUE TITLE
Can't scrap TripAdvisor

### ISSUE THREAD

**Issue by mareckiZ** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#5]
Hello, 
I proceed till the final part and stoped at error:
"UnicodeEncodeError: 'charmap' codec can't encode character '\xc8' in position 3: character maps to <undefined>
>>>     # to change the page
>>>     if (check_exists_by_xpath('//a[@class="ui_button nav next primary "]')):
  File "<stdin>", line 1
    if (check_exists_by_xpath('//a[@class="ui_button nav next primary "]')):
    ^
IndentationError: unexpected indent
>>>         driver.find_element_by_xpath('//a[@class="ui_button nav next primary "]').click()
  File "<stdin>", line 1
    driver.find_element_by_xpath('//a[@class="ui_button nav next primary "]').click()
    ^
IndentationError: unexpected indent"

Can you explain what went wrong?
BR
Marek

**Comment by giuseppegambino** [comment]
Hi @mareckiZ , I did not understand the problem, maybe a typo?

In any case I have updated the code! Let me know if you have solved now.
