### ISSUE TITLE
Scraping error at a hotel review

### ISSUE THREAD

**Issue by gmarkop** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#6]
First of all many thanks for this valuable tool! Although your scraper works perfectly with the example from Colosseo, when I try to extract hotel reviews, the following error appears:

[ElementClickInterceptedException: element click intercepted: Element <a class="ui_button nav next primary " href="/Hotel_Review-g189400-d228911-Reviews-or5-The_Golden_Age_Hotel_of_Athens-Athens_Attica.html">...</a> is not clickable at point (845, 870). Other element would receive the click: <div class="_26xCMGoF toYy1402">...</div>
  (Session info: chrome=86.0.4240.111)]

Thanks in advance for any help.

**Comment by giuseppegambino** [comment]
Sorry for the delay, analysing the problem I saw that there are differences in the html page based on the type of place, whether it is a restaurant or hotel / monuments.

Now you can try the new updated code, let me know if whit that you have solved the problem.

**Comment by gmarkop** [comment]
I tried it and it works perfectly! Many thanks!
