### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by chrstnbwnkl** [giuseppegambino/Scraping-TripAdvisor-with-Python-2020#8]
I'm thinking of using this (or part of this) code in a project, but couldn't find a license (I just want to make sure what I can and can't do with it :) ).

**Comment by giuseppegambino** [comment]
Hi @chrstnbwnkl , 
Yes you can use, edit  (or anything else) the code :)

I'm new to the license issue but I saw that github has a guide for choosing a license, i will do it soon!

Thank you, 
Giuseppe.
